fragment TaskCategoryFields on TaskCategoryDto {
  id
  name
  parent {
    id
    name
  }
}

fragment TaskFields on TaskDto {
  id
  title
  description
  priority
  expense
  factor
  due
  categories {
    ...TaskCategoryFields
  }
  type
  repeat
  status
}

query GetPaginatedTasks($skip: Int, $take: Int) {
  tasks(skip: $skip, take: $take) {
    totalCount
    skip
    take
    items {
      ...TaskFields
    }
  }
}

mutation CreateTask($input: TaskInput!) {
  createTask(input: $input) {
    ...TaskFields
  }
}

mutation UpdateTask($input: TaskInput!) {
  updateTask(input: $input) {
    ...TaskFields
  }
}

mutation DeleteTask($id: ID!) {
  deleteTask(id: $id)
}

query GetTaskCategories($parentId: String, $nameLike: String) {
  taskCategories(parentId: $parentId, nameLike: $nameLike) {
    ...TaskCategoryFields
  }
}

mutation CreateTaskCategory($name: String!, $parentId: String) {
  createTaskCategory(input: { name: $name, parentId: $parentId }) {
    ...TaskCategoryFields
  }
}
